// <auto-generated />
namespace TestFixture.Services;

/// <summary>Generated-style consumer (*.g.cs) — the change_signature generated-file blocker test.</summary>
public class SignatureGeneratedConsumer
{
    private readonly SignatureChangeSurface surface = new();

    public int StampCall() => surface.Stamp(1, 2);
}
