from __future__ import annotations

import sys
from pathlib import Path
from types import SimpleNamespace

# generate_references.py is a top-level script under scripts/ab-test/, not in the package;
# import it by path-insertion the same way it bootstraps itself.
_SCRIPT_DIR = Path(__file__).resolve().parent.parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))

import generate_references as genref  # noqa: E402


def test_breaking_oracles_registry_mirrors_the_patch() -> None:
    changes = genref.BREAKING_ORACLES["P3-check-breaking-changes"]
    # Three planted public-surface changes, forward-modeled on the clean clone.
    assert [c.arguments["changeKind"] for c in changes] == [
        "RemoveSymbol",
        "SignatureChange",
        "SignatureChange",
    ]
    assert all(c.arguments["containingType"] == "CommonHelper" for c in changes)
    assert all(c.arguments.get("includeTests") is True for c in changes)
    assert all(c.break_class for c in changes)
    # The internal decoy must be named so the judge can penalize over-reporting it.
    assert "EncryptionKeyMetadata" in genref.BREAKING_DECOYS["P3-check-breaking-changes"]


def test_generate_breaking_reference_combines_table_decoy_and_sections(
    tmp_path: Path, monkeypatch
) -> None:
    bodies = iter(["IMPACT-REMOVE", "IMPACT-SIG-1", "IMPACT-SIG-2"])
    calls: list[str] = []

    def fake_call_tool(name: str, arguments: dict, timeout: float) -> str:
        calls.append(name)
        return next(bodies)

    client = SimpleNamespace(call_tool=fake_call_tool)
    # Redirect the reference write into the tmp dir so the real oracle isn't clobbered.
    monkeypatch.setattr(genref, "TASKS_DIR", tmp_path)

    out = genref._generate_breaking_reference(client, "P3-check-breaking-changes")
    text = out.read_text(encoding="utf-8")

    assert out == tmp_path / "P3-check-breaking-changes.reference.md"
    assert calls == ["analyze_change_impact"] * 3
    # Provenance + the hand-annotated table + the decoy + every change's body + the break classes.
    assert "GENERATED by" in text
    assert "Planted breaking-change set" in text
    assert "Decoy — must NOT be reported" in text
    assert "EncryptionKeyMetadata" in text
    for body in ("IMPACT-REMOVE", "IMPACT-SIG-1", "IMPACT-SIG-2"):
        assert body in text
    assert "source-incompatible" in text
    assert "binary-incompatible" in text
    assert "behavior change" in text
