name: CI

on:
  push:
    branches: [main, master]
  pull_request:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore tests/Zphil.Roz.Tests/Zphil.Roz.Tests.csproj

      - name: Build
        run: dotnet build tests/Zphil.Roz.Tests/Zphil.Roz.Tests.csproj --no-restore

      - name: Test
        run: dotnet test tests/Zphil.Roz.Tests/Zphil.Roz.Tests.csproj --no-build --logger "console;verbosity=normal" --collect:"XPlat Code Coverage" --settings tests/Zphil.Roz.Tests/ci.runsettings
