name: CI

on:
  push:
    branches: [main, master]
  pull_request:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore tests/Zphil.Roz.Tests/Zphil.Roz.Tests.csproj

      - name: Build
        run: dotnet build tests/Zphil.Roz.Tests/Zphil.Roz.Tests.csproj --no-restore

      - name: Test
        run: dotnet test tests/Zphil.Roz.Tests/Zphil.Roz.Tests.csproj --no-build --logger "console;verbosity=normal" --collect:"XPlat Code Coverage" --settings tests/Zphil.Roz.Tests/ci.runsettings
